from colorama import Fore, Back, Style

art = {
    "ASpades": "Ace of Spades 🂡",
    "2Spades": "2 of Spades 🂢",
    "3Spades": "3 of Spades 🂣",
    "4Spades": "4 of Spades 🂤 ",
    "5Spades": "5 of Spades 🂥",
    "6Spades": "6 of Spades 🂦",
    "7Spades": "7 of Spades 🂧",
    "8Spades": "8 of Spades 🂨",
    "9Spades": "9 of Spades 🂩",
    "10Spades": "10 of Spades 🂪",
    "JSpades": "Jack of Spades 🂫",
    "QSpades": "Queen of Spades 🂭",
    "KSpades": "King of Spades 🂮",
    "AHearts": "Ace of Hearts 🂱",
    "2Hearts": "2 of Hearts 🂲",
    "3Hearts": "3 of Hearts 🂳",
    "4Hearts": "4 of Hearts 🂴",
    "5Hearts": "5 of Hearts 🂵",
    "6Hearts": "6 of Hearts 🂶",
    "7Hearts": "7 of Hearts 🂷",
    "8Hearts": "8 of Hearts 🂸",
    "9Hearts": "9 of Hearts 🂹",
    "10Hearts": "10 of Hearts 🂺",
    "JHearts": "Jack of Hearts 🂻",
    "QHearts": "Queen of Hearts 🂽",
    "KHearts": "King of Hearts 🂾",
    "ADiamonds": "Ace of Diamonds 🃁",
    "2Diamonds": "2 of Diamonds 🃂",
    "3Diamonds": "3 of Diamonds 🃃",
    "4Diamonds": "4 of Diamonds 🃄",
    "5Diamonds": "5 of Diamonds 🃅",
    "6Diamonds": "6 of Diamonds 🃆",
    "7Diamonds": "7 of Diamonds 🃇",
    "8Diamonds": "8 of Diamonds 🃈",
    "9Diamonds": "9 of Diamonds 🃉",
    "10Diamonds": "10 of Diamonds 🃊",
    "JDiamonds": "Jack of Diamonds 🃋",
    "QDiamonds": "Queen of Diamonds 🃍",
    "KDiamonds": "King of Diamonds 🃎",
    "AClubs": "Ace of Clubs 🃑",
    "2Clubs": "2 of Clubs 🃒",
    "3Clubs": "3 of Clubs 🃓",
    "4Clubs": "4 of Clubs 🃔",
    "5Clubs": "5 of Clubs 🃕",
    "6Clubs": "6 of Clubs 🃖",
    "7Clubs": "7 of Clubs 🃗",
    "8Clubs": "8 of Clubs 🃘",
    "9Clubs": "9 of Clubs 🃙",
    "10Clubs": "10 of Clubs 🃚",
    "JClubs": "Jack of Clubs 🃛",
    "QClubs": "Queen of Clubs 🃝",
    "KClubs": "King of Clubs 🃞"
    }